### ISSUE TITLE
[feature request] minimum file size to interrupt downloads

### ISSUE THREAD

**Issue by tubbadu** [igorlogius/forward-download#4]

**Comment by igorlogius** [comment]
yeah, this could easily be added as a configurable setting on the option page. 

The only issue here might be ... that i am not sure if the full file size ... is always available ... when a download starts. 
That might not be the case, but i'll check that.

**Comment by igorlogius** [comment]
As i suspected the filesize might not be available when a download is started ... so this functionality can not be implemented in a way that it would work reliably. 

A possibility way to handle this would be to allow the user to set a default behaviour for this situation (filesize := -1)  Possible options would be: 

1. Show a notification and do nothing (dont download) 
2. Always Forward the Download 
3. Do not  forward the download and let the browser handle it. 

> fileSize
>    A number indicating the total number of bytes in the whole file, after decompression. A value of -1 here means that the total file size is unknown.

ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/DownloadItem

**Comment by tubbadu** [comment]
I think this is perfect! I don't know how other addons (e.g. uGet) handles this cases of unknown filesize, but adding this in option page is an awesome idea

**Comment by igorlogius** [comment]
I'll think i'll forgo the option page (for now)  and instead make the handler script  responsible for decision making. 
The  hander script will get supplied with all available information ... and it can return a value wich indicates if it has taken over the download or not. (on which passis the browser download will be canceled or not)

**Comment by igorlogius** [comment]
![snip_20220928-160548](https://user-images.githubusercontent.com/67047467/192800372-282a2326-1837-4448-bd26-2292481ecb55.png)
